//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWS.WSKrack {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRespuesta", Namespace="http://schemas.datacontract.org/2004/07/MyWS")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClienteWS.WSKrack.Zapato))]
    public partial class BaseRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zapato", Namespace="http://schemas.datacontract.org/2004/07/MyWS")]
    [System.SerializableAttribute()]
    public partial class Zapato : ClienteWS.WSKrack.BaseRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TallaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Talla {
            get {
                return this.TallaField;
            }
            set {
                if ((this.TallaField.Equals(value) != true)) {
                    this.TallaField = value;
                    this.RaisePropertyChanged("Talla");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSKrack.IWSKrack")]
    public interface IWSKrack {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKrack/ObtenerZapato", ReplyAction="http://tempuri.org/IWSKrack/ObtenerZapatoResponse")]
        ClienteWS.WSKrack.Zapato ObtenerZapato(string Ident);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSKrack/ObtenerZapato", ReplyAction="http://tempuri.org/IWSKrack/ObtenerZapatoResponse")]
        System.Threading.Tasks.Task<ClienteWS.WSKrack.Zapato> ObtenerZapatoAsync(string Ident);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSKrackChannel : ClienteWS.WSKrack.IWSKrack, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSKrackClient : System.ServiceModel.ClientBase<ClienteWS.WSKrack.IWSKrack>, ClienteWS.WSKrack.IWSKrack {
        
        public WSKrackClient() {
        }
        
        public WSKrackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSKrackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSKrackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSKrackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClienteWS.WSKrack.Zapato ObtenerZapato(string Ident) {
            return base.Channel.ObtenerZapato(Ident);
        }
        
        public System.Threading.Tasks.Task<ClienteWS.WSKrack.Zapato> ObtenerZapatoAsync(string Ident) {
            return base.Channel.ObtenerZapatoAsync(Ident);
        }
    }
}
